version: '3.8'

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - "8080:8080" # Port pour accéder à l'interface AIO
      - "443:443"         # Port pour HTTPS

    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # Volume correct
      - /var/run/docker.sock:/var/run/docker.sock # Ajout du socket Docker
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0 # Adapter si nécessaire
      - NEXTCLOUD_DATADIR=/mnt/data

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer